/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTableauBordRouteImport } from './routes/_authenticated/tableau-bord'
import { Route as AuthenticatedParcoursRouteImport } from './routes/_authenticated/parcours'
import { Route as AuthenticatedExamenBlancRouteImport } from './routes/_authenticated/examen-blanc'
import { Route as AuthenticatedLeconLeconIdRouteImport } from './routes/_authenticated/lecon.$leconId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTableauBordRoute =
  AuthenticatedTableauBordRouteImport.update({
    id: '/tableau-bord',
    path: '/tableau-bord',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParcoursRoute = AuthenticatedParcoursRouteImport.update({
  id: '/parcours',
  path: '/parcours',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamenBlancRoute =
  AuthenticatedExamenBlancRouteImport.update({
    id: '/examen-blanc',
    path: '/examen-blanc',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeconLeconIdRoute =
  AuthenticatedLeconLeconIdRouteImport.update({
    id: '/lecon/$leconId',
    path: '/lecon/$leconId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/examen-blanc': typeof AuthenticatedExamenBlancRoute
  '/parcours': typeof AuthenticatedParcoursRoute
  '/tableau-bord': typeof AuthenticatedTableauBordRoute
  '/lecon/$leconId': typeof AuthenticatedLeconLeconIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/examen-blanc': typeof AuthenticatedExamenBlancRoute
  '/parcours': typeof AuthenticatedParcoursRoute
  '/tableau-bord': typeof AuthenticatedTableauBordRoute
  '/lecon/$leconId': typeof AuthenticatedLeconLeconIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/examen-blanc': typeof AuthenticatedExamenBlancRoute
  '/_authenticated/parcours': typeof AuthenticatedParcoursRoute
  '/_authenticated/tableau-bord': typeof AuthenticatedTableauBordRoute
  '/_authenticated/lecon/$leconId': typeof AuthenticatedLeconLeconIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/examen-blanc'
    | '/parcours'
    | '/tableau-bord'
    | '/lecon/$leconId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/examen-blanc'
    | '/parcours'
    | '/tableau-bord'
    | '/lecon/$leconId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/examen-blanc'
    | '/_authenticated/parcours'
    | '/_authenticated/tableau-bord'
    | '/_authenticated/lecon/$leconId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tableau-bord': {
      id: '/_authenticated/tableau-bord'
      path: '/tableau-bord'
      fullPath: '/tableau-bord'
      preLoaderRoute: typeof AuthenticatedTableauBordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parcours': {
      id: '/_authenticated/parcours'
      path: '/parcours'
      fullPath: '/parcours'
      preLoaderRoute: typeof AuthenticatedParcoursRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/examen-blanc': {
      id: '/_authenticated/examen-blanc'
      path: '/examen-blanc'
      fullPath: '/examen-blanc'
      preLoaderRoute: typeof AuthenticatedExamenBlancRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lecon/$leconId': {
      id: '/_authenticated/lecon/$leconId'
      path: '/lecon/$leconId'
      fullPath: '/lecon/$leconId'
      preLoaderRoute: typeof AuthenticatedLeconLeconIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedExamenBlancRoute: typeof AuthenticatedExamenBlancRoute
  AuthenticatedParcoursRoute: typeof AuthenticatedParcoursRoute
  AuthenticatedTableauBordRoute: typeof AuthenticatedTableauBordRoute
  AuthenticatedLeconLeconIdRoute: typeof AuthenticatedLeconLeconIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedExamenBlancRoute: AuthenticatedExamenBlancRoute,
  AuthenticatedParcoursRoute: AuthenticatedParcoursRoute,
  AuthenticatedTableauBordRoute: AuthenticatedTableauBordRoute,
  AuthenticatedLeconLeconIdRoute: AuthenticatedLeconLeconIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
