/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTableauBordRouteImport } from './routes/_authenticated/tableau-bord'
import { Route as AuthenticatedParcoursRouteImport } from './routes/_authenticated/parcours'
import { Route as AuthenticatedExamenBlancRouteImport } from './routes/_authenticated/examen-blanc'
import { Route as AuthenticatedChecklistRouteImport } from './routes/_authenticated/checklist'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedLeconLeconIdRouteImport } from './routes/_authenticated/lecon.$leconId'
import { Route as AuthenticatedAdminQuestionsRouteImport } from './routes/_authenticated/admin/questions'
import { Route as AuthenticatedAdminModulesRouteImport } from './routes/_authenticated/admin/modules'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTableauBordRoute =
  AuthenticatedTableauBordRouteImport.update({
    id: '/tableau-bord',
    path: '/tableau-bord',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParcoursRoute = AuthenticatedParcoursRouteImport.update({
  id: '/parcours',
  path: '/parcours',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamenBlancRoute =
  AuthenticatedExamenBlancRouteImport.update({
    id: '/examen-blanc',
    path: '/examen-blanc',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChecklistRoute = AuthenticatedChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedLeconLeconIdRoute =
  AuthenticatedLeconLeconIdRouteImport.update({
    id: '/lecon/$leconId',
    path: '/lecon/$leconId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminQuestionsRoute =
  AuthenticatedAdminQuestionsRouteImport.update({
    id: '/questions',
    path: '/questions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminModulesRoute =
  AuthenticatedAdminModulesRouteImport.update({
    id: '/modules',
    path: '/modules',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/checklist': typeof AuthenticatedChecklistRoute
  '/examen-blanc': typeof AuthenticatedExamenBlancRoute
  '/parcours': typeof AuthenticatedParcoursRoute
  '/tableau-bord': typeof AuthenticatedTableauBordRoute
  '/admin/modules': typeof AuthenticatedAdminModulesRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/lecon/$leconId': typeof AuthenticatedLeconLeconIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checklist': typeof AuthenticatedChecklistRoute
  '/examen-blanc': typeof AuthenticatedExamenBlancRoute
  '/parcours': typeof AuthenticatedParcoursRoute
  '/tableau-bord': typeof AuthenticatedTableauBordRoute
  '/admin/modules': typeof AuthenticatedAdminModulesRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/lecon/$leconId': typeof AuthenticatedLeconLeconIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/checklist': typeof AuthenticatedChecklistRoute
  '/_authenticated/examen-blanc': typeof AuthenticatedExamenBlancRoute
  '/_authenticated/parcours': typeof AuthenticatedParcoursRoute
  '/_authenticated/tableau-bord': typeof AuthenticatedTableauBordRoute
  '/_authenticated/admin/modules': typeof AuthenticatedAdminModulesRoute
  '/_authenticated/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/_authenticated/lecon/$leconId': typeof AuthenticatedLeconLeconIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/checklist'
    | '/examen-blanc'
    | '/parcours'
    | '/tableau-bord'
    | '/admin/modules'
    | '/admin/questions'
    | '/lecon/$leconId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/checklist'
    | '/examen-blanc'
    | '/parcours'
    | '/tableau-bord'
    | '/admin/modules'
    | '/admin/questions'
    | '/lecon/$leconId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/checklist'
    | '/_authenticated/examen-blanc'
    | '/_authenticated/parcours'
    | '/_authenticated/tableau-bord'
    | '/_authenticated/admin/modules'
    | '/_authenticated/admin/questions'
    | '/_authenticated/lecon/$leconId'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tableau-bord': {
      id: '/_authenticated/tableau-bord'
      path: '/tableau-bord'
      fullPath: '/tableau-bord'
      preLoaderRoute: typeof AuthenticatedTableauBordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parcours': {
      id: '/_authenticated/parcours'
      path: '/parcours'
      fullPath: '/parcours'
      preLoaderRoute: typeof AuthenticatedParcoursRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/examen-blanc': {
      id: '/_authenticated/examen-blanc'
      path: '/examen-blanc'
      fullPath: '/examen-blanc'
      preLoaderRoute: typeof AuthenticatedExamenBlancRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checklist': {
      id: '/_authenticated/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof AuthenticatedChecklistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/lecon/$leconId': {
      id: '/_authenticated/lecon/$leconId'
      path: '/lecon/$leconId'
      fullPath: '/lecon/$leconId'
      preLoaderRoute: typeof AuthenticatedLeconLeconIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/questions': {
      id: '/_authenticated/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AuthenticatedAdminQuestionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/modules': {
      id: '/_authenticated/admin/modules'
      path: '/modules'
      fullPath: '/admin/modules'
      preLoaderRoute: typeof AuthenticatedAdminModulesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminModulesRoute: typeof AuthenticatedAdminModulesRoute
  AuthenticatedAdminQuestionsRoute: typeof AuthenticatedAdminQuestionsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminModulesRoute: AuthenticatedAdminModulesRoute,
    AuthenticatedAdminQuestionsRoute: AuthenticatedAdminQuestionsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedChecklistRoute: typeof AuthenticatedChecklistRoute
  AuthenticatedExamenBlancRoute: typeof AuthenticatedExamenBlancRoute
  AuthenticatedParcoursRoute: typeof AuthenticatedParcoursRoute
  AuthenticatedTableauBordRoute: typeof AuthenticatedTableauBordRoute
  AuthenticatedLeconLeconIdRoute: typeof AuthenticatedLeconLeconIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedChecklistRoute: AuthenticatedChecklistRoute,
  AuthenticatedExamenBlancRoute: AuthenticatedExamenBlancRoute,
  AuthenticatedParcoursRoute: AuthenticatedParcoursRoute,
  AuthenticatedTableauBordRoute: AuthenticatedTableauBordRoute,
  AuthenticatedLeconLeconIdRoute: AuthenticatedLeconLeconIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
