-- Garantir l'existence des 4 modules, réassocier les questions orphelines,
-- et réinsérer les 106 questions complémentaires (au cas où la migration 300000 a échoué)

-- 1. Créer les modules manquants s'ils n'existent pas
INSERT INTO public.modules (titre, description, categorie, ordre, icone)
SELECT 'Conditions et niveaux de langue', 'Niveaux de français requis pour chaque titre de séjour et la nationalité (A2, B1, B2).', 'langue', 1, 'Languages'
WHERE NOT EXISTS (SELECT 1 FROM public.modules WHERE categorie = 'langue');

INSERT INTO public.modules (titre, description, categorie, ordre, icone)
SELECT 'Carte de résident 10 ans', 'Conditions, procédure et droits liés à la carte de résident de longue durée.', 'carte_resident', 2, 'FileCheck2'
WHERE NOT EXISTS (SELECT 1 FROM public.modules WHERE categorie = 'carte_resident');

INSERT INTO public.modules (titre, description, categorie, ordre, icone)
SELECT 'Naturalisation française', 'Procédure de naturalisation par décret et par déclaration (mariage).', 'naturalisation', 3, 'Award'
WHERE NOT EXISTS (SELECT 1 FROM public.modules WHERE categorie = 'naturalisation');

INSERT INTO public.modules (titre, description, categorie, ordre, icone)
SELECT 'Examen civique', 'Préparation à l''examen de connaissances civiques : institutions, valeurs, histoire et symboles de la République française.', 'examen_civique', 4, 'GraduationCap'
WHERE NOT EXISTS (SELECT 1 FROM public.modules WHERE categorie = 'examen_civique');

-- 2. Créer l'index unique sur enonce s'il n'existe pas
CREATE UNIQUE INDEX IF NOT EXISTS questions_enonce_unique ON public.questions (enonce);

-- 3. Réassocier les questions avec des UUID fictifs vers les vrais modules
UPDATE public.questions SET module_id = (SELECT id FROM public.modules WHERE categorie = 'langue' LIMIT 1)
WHERE module_id = '11111111-1111-1111-1111-111111111101';

UPDATE public.questions SET module_id = (SELECT id FROM public.modules WHERE categorie = 'carte_resident' LIMIT 1)
WHERE module_id = '11111111-1111-1111-1111-111111111102';

UPDATE public.questions SET module_id = (SELECT id FROM public.modules WHERE categorie = 'naturalisation' LIMIT 1)
WHERE module_id = '11111111-1111-1111-1111-111111111103';

UPDATE public.questions SET module_id = (SELECT id FROM public.modules WHERE categorie = 'examen_civique' LIMIT 1)
WHERE module_id = '11111111-1111-1111-1111-111111111104';

-- 4. Insérer les 106 questions complémentaires (doublons ignorés via l'index unique sur enonce)
DO $$
DECLARE
  v_civique UUID;
  v_langue UUID;
  v_carte UUID;
  v_nat UUID;
BEGIN
  SELECT id INTO v_civique FROM modules WHERE categorie = 'examen_civique' LIMIT 1;
  SELECT id INTO v_langue FROM modules WHERE categorie = 'langue' LIMIT 1;
  SELECT id INTO v_carte FROM modules WHERE categorie = 'carte_resident' LIMIT 1;
  SELECT id INTO v_nat FROM modules WHERE categorie = 'naturalisation' LIMIT 1;

  -- EXAMEN CIVIQUE (39)
  INSERT INTO questions (module_id, enonce, type, options_json, bonne_reponse, explication, source_officielle, date_verification, difficulte) VALUES
  (v_civique, 'La laïcité permet-elle de pratiquer la religion de son choix ?', 'qcm', '["Non, toute religion est interdite","Oui, dans le respect de la loi et de l''ordre public","Seulement la religion majoritaire","Uniquement chez soi en secret"]', 'Oui, dans le respect de la loi et de l''ordre public', 'La laïcité garantit la liberté de culte : chacun peut pratiquer la religion de son choix, ou aucune, dans le respect de la loi.', 'Livret du citoyen — formation-civique.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 2),
  (v_civique, 'Que signifie « l''égalité devant la loi » ?', 'qcm', '["La loi favorise les plus riches","La loi est la même pour tous","Chaque région a sa loi","La loi ne s''applique pas aux étrangers"]', 'La loi est la même pour tous', 'L''égalité devant la loi signifie que la loi est la même pour toutes et tous, sans privilège ni discrimination.', 'Livret du citoyen — formation-civique.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 1),
  (v_civique, 'Le drapeau tricolore est apparu pendant :', 'qcm', '["la monarchie absolue","la Révolution française","la Ve République","la Seconde Guerre mondiale"]', 'la Révolution française', 'Le drapeau bleu-blanc-rouge est né pendant la Révolution française ; il associe les couleurs de Paris au blanc royal.', 'Livret du citoyen — formation-civique.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 2),
  (v_civique, 'Qui a composé La Marseillaise ?', 'qcm', '["Victor Hugo","Rouget de Lisle","Jean-Jacques Rousseau","Napoléon Bonaparte"]', 'Rouget de Lisle', 'La Marseillaise a été composée par Rouget de Lisle en 1792, à Strasbourg.', 'Livret du citoyen — formation-civique.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 3),
  (v_civique, 'La liberté d''opinion signifie que :', 'qcm', '["nul ne peut être inquiété pour ses opinions, dans le respect de la loi","on peut diffamer librement","l''État impose une opinion","seuls les élus ont une opinion"]', 'nul ne peut être inquiété pour ses opinions, dans le respect de la loi', 'La liberté d''opinion, affirmée dès 1789, protège le droit d''avoir et d''exprimer ses idées, dans le respect de la loi.', 'Livret du citoyen — formation-civique.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 2),
  (v_civique, 'La solidarité nationale (sécurité sociale, services publics) découle surtout du principe de :', 'qcm', '["liberté","égalité","fraternité","laïcité"]', 'fraternité', 'La fraternité inspire la solidarité nationale : entraide, protection sociale et services publics ouverts à tous.', 'Livret du citoyen — formation-civique.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 2),
  (v_civique, 'Le gouvernement est dirigé par :', 'qcm', '["le président de la République","le Premier ministre","le président du Sénat","le maire de Paris"]', 'le Premier ministre', 'Le gouvernement est dirigé par le Premier ministre, qui conduit la politique de la nation avec ses ministres.', 'Livret du citoyen — formation-civique.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 2),
  (v_civique, 'Qui peut dissoudre l''Assemblée nationale ?', 'qcm', '["Le Premier ministre","Le président de la République","Le Sénat","Le Conseil constitutionnel"]', 'Le président de la République', 'Le président de la République peut dissoudre l''Assemblée nationale, ce qui provoque de nouvelles élections législatives.', 'Livret du citoyen — formation-civique.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 3),
  (v_civique, 'Pour combien d''années les sénateurs sont-ils élus ?', 'qcm', '["4 ans","5 ans","6 ans","9 ans"]', '6 ans', 'Les sénateurs sont élus pour 6 ans, au suffrage universel indirect ; le Sénat est renouvelé par moitié tous les 3 ans.', 'Livret du citoyen — formation-civique.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 3),
  (v_civique, 'Le Sénat est élu au suffrage :', 'qcm', '["universel direct","universel indirect","par tirage au sort","par le président"]', 'universel indirect', 'Les sénateurs sont élus au suffrage universel indirect, par des « grands électeurs » (élus locaux).', 'Livret du citoyen — formation-civique.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 3),
  (v_civique, 'Pour combien d''années le conseil municipal est-il élu ?', 'qcm', '["3 ans","5 ans","6 ans","7 ans"]', '6 ans', 'Les conseillers municipaux sont élus pour 6 ans ; le conseil municipal élit ensuite le maire.', 'Livret du citoyen — formation-civique.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 2),
  (v_civique, 'Au nom de qui la justice est-elle rendue en France ?', 'qcm', '["Au nom du président","Au nom du peuple français","Au nom du gouvernement","Au nom de l''Europe"]', 'Au nom du peuple français', 'En France, la justice est rendue au nom du peuple français, par des juges indépendants.', 'Livret du citoyen — formation-civique.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 2),
  (v_civique, 'Qui promulgue les lois votées par le Parlement ?', 'qcm', '["Le Premier ministre","Le président de la République","Le Conseil constitutionnel","Le maire"]', 'Le président de la République', 'Le président de la République promulgue les lois, c''est-à-dire les rend applicables, après leur vote par le Parlement.', 'Livret du citoyen — formation-civique.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 3),
  (v_civique, 'Dans une démocratie, le pouvoir appartient :', 'qcm', '["au roi","au peuple","à l''armée","aux plus riches"]', 'au peuple', 'La démocratie signifie que le pouvoir appartient au peuple, qui l''exerce notamment par le vote.', 'Livret du citoyen — formation-civique.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 1),
  (v_civique, 'La Journée défense et citoyenneté (JDC) concerne :', 'qcm', '["tous les habitants","les jeunes Français de 16 à 25 ans","les retraités","les touristes"]', 'les jeunes Français de 16 à 25 ans', 'La JDC concerne les jeunes Français, garçons et filles, entre 16 et 25 ans.', 'Livret du citoyen — formation-civique.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 3),
  (v_civique, 'Le droit de grève est :', 'qcm', '["interdit","un droit reconnu, encadré par la loi","réservé aux fonctionnaires","décidé par l''employeur"]', 'un droit reconnu, encadré par la loi', 'Le droit de grève est un droit reconnu, qui s''exerce dans le cadre fixé par la loi.', 'Livret du citoyen — formation-civique.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 2),
  (v_civique, 'Respecter les symboles de la République (drapeau, hymne) est :', 'qcm', '["facultatif","un devoir civique","interdit","réservé aux élus"]', 'un devoir civique', 'Respecter les symboles de la République fait partie des devoirs civiques de chacun.', 'Livret du citoyen — formation-civique.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 1),
  (v_civique, 'La liberté syndicale permet :', 'qcm', '["d''interdire les syndicats","d''adhérer ou non à un syndicat librement","de licencier les grévistes","d''imposer un syndicat unique"]', 'd''adhérer ou non à un syndicat librement', 'La liberté syndicale garantit à chacun le droit d''adhérer, ou non, au syndicat de son choix.', 'Livret du citoyen — formation-civique.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 2),
  (v_civique, 'Quel code juridique majeur a été créé sous Napoléon Bonaparte ?', 'qcm', '["Le Code de la route","Le Code civil","Le Code du travail","Le Code pénal européen"]', 'Le Code civil', 'Le Code civil, promulgué en 1804 sous Napoléon Bonaparte, organise le droit des personnes et des biens.', 'Livret du citoyen — formation-civique.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 3),
  (v_civique, 'La fête du Travail est célébrée le :', 'qcm', '["1er mai","8 mai","14 juillet","11 novembre"]', '1er mai', 'Le 1er mai est la fête du Travail, jour férié en France.', 'Livret du citoyen — formation-civique.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 1),
  (v_civique, 'Que commémore-t-on le 11 novembre ?', 'qcm', '["La fin de la Seconde Guerre mondiale","L''armistice de la Première Guerre mondiale (1918)","La prise de la Bastille","La libération de Paris"]', 'L''armistice de la Première Guerre mondiale (1918)', 'Le 11 novembre commémore l''armistice de 1918, qui a mis fin aux combats de la Première Guerre mondiale.', 'Livret du citoyen — formation-civique.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 2),
  (v_civique, 'Que commémore-t-on le 8 mai ?', 'qcm', '["La fête nationale","La victoire de 1945 (fin de la 2nde Guerre mondiale en Europe)","La fête du Travail","La Révolution française"]', 'La victoire de 1945 (fin de la 2nde Guerre mondiale en Europe)', 'Le 8 mai commémore la victoire des Alliés et la fin de la Seconde Guerre mondiale en Europe, en 1945.', 'Livret du citoyen — formation-civique.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 2),
  (v_civique, 'Quel océan borde l''ouest de la France métropolitaine ?', 'qcm', '["L''océan Pacifique","L''océan Atlantique","L''océan Indien","La mer Noire"]', 'L''océan Atlantique', 'L''océan Atlantique borde l''ouest de la France ; la Manche borde le nord et la Méditerranée le sud.', 'Livret du citoyen — formation-civique.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 1),
  (v_civique, 'La Corse est :', 'qcm', '["une région d''Espagne","une île française de la Méditerranée","un pays indépendant","une ville du sud"]', 'une île française de la Méditerranée', 'La Corse est une île française située en mer Méditerranée ; elle constitue une collectivité territoriale.', 'Livret du citoyen — formation-civique.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 2),
  (v_civique, 'Combien de régions compte la France métropolitaine depuis 2016 ?', 'qcm', '["13","18","22","27"]', '13', 'Depuis la réforme de 2016, la France métropolitaine compte 13 régions.', 'Livret du citoyen — formation-civique.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 3),
  (v_civique, 'Quelle est la langue officielle de la France ?', 'qcm', '["Le latin","Le français","L''anglais","L''occitan"]', 'Le français', 'L''article 2 de la Constitution dispose que « la langue de la République est le français ».', 'Livret du citoyen — formation-civique.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 1),
  (v_civique, 'Dans quelle ville le traité fondateur de la Communauté économique européenne a-t-il été signé en 1957 ?', 'qcm', '["Bruxelles","Rome","Paris","Maastricht"]', 'Rome', 'Le traité de Rome (1957) a institué la Communauté économique européenne, ancêtre de l''Union européenne.', 'Livret du citoyen — formation-civique.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 3),
  (v_civique, 'Quelle est la couleur du fond du drapeau européen ?', 'qcm', '["Rouge","Bleu","Vert","Blanc"]', 'Bleu', 'Le drapeau européen présente 12 étoiles dorées sur un fond bleu.', 'Livret du citoyen — formation-civique.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 1),
  (v_civique, 'En cas d''urgence médicale grave, quel numéro composer ?', 'qcm', '["15 (SAMU)","18 (pompiers)","17 (police)","3919"]', '15 (SAMU)', 'Le 15 est le numéro du SAMU pour les urgences médicales. Le 112 fonctionne aussi partout en Europe.', 'Livret du citoyen — formation-civique.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 1),
  (v_civique, 'Quel numéro composer pour joindre la police ou la gendarmerie ?', 'qcm', '["15","17","18","115"]', '17', 'Le 17 permet de joindre la police ou la gendarmerie en cas d''urgence.', 'Livret du citoyen — formation-civique.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 1),
  (v_civique, 'À l''école publique, l''enseignement est :', 'qcm', '["payant et religieux","gratuit et laïque","réservé aux Français","facultatif"]', 'gratuit et laïque', 'L''enseignement public est gratuit et laïque ; l''instruction est obligatoire de 3 à 16 ans.', 'Livret du citoyen — formation-civique.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 1),
  (v_civique, 'Le harcèlement (à l''école, au travail) est :', 'qcm', '["toléré","interdit et puni par la loi","autorisé entre adultes","une affaire privée"]', 'interdit et puni par la loi', 'Le harcèlement est interdit et sanctionné par la loi, qu''il soit scolaire, moral ou sexuel.', 'Livret du citoyen — formation-civique.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 2),
  (v_civique, 'Les violences au sein du couple sont :', 'qcm', '["une affaire strictement privée","interdites et punies par la loi","tolérées dans certains cas","du ressort de la famille"]', 'interdites et punies par la loi', 'Les violences conjugales sont des délits punis par la loi ; un numéro d''écoute, le 3919, peut être appelé.', 'Livret du citoyen — formation-civique.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 2),
  (v_civique, 'La devise « Liberté, Égalité, Fraternité » est inscrite :', 'qcm', '["dans le Code de la route","dans la Constitution","dans le règlement des écoles uniquement","nulle part"]', 'dans la Constitution', 'La devise figure à l''article 2 de la Constitution, parmi les symboles de la République.', 'Livret du citoyen — formation-civique.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 2),
  (v_civique, 'Les élections présidentielles ont lieu, en principe, tous les :', 'qcm', '["3 ans","5 ans","6 ans","7 ans"]', '5 ans', 'L''élection présidentielle a lieu tous les 5 ans, durée du mandat (quinquennat) du président.', 'Livret du citoyen — formation-civique.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 2),
  (v_civique, 'La Déclaration des droits de l''homme et du citoyen date de :', 'qcm', '["1789","1848","1905","1958"]', '1789', 'La Déclaration des droits de l''homme et du citoyen a été adoptée en 1789, pendant la Révolution française.', 'Livret du citoyen — formation-civique.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 1),
  (v_civique, 'Quelle est la ville la plus peuplée de France ?', 'qcm', '["Marseille","Lyon","Paris","Toulouse"]', 'Paris', 'Paris est la ville la plus peuplée de France et la capitale du pays.', 'Livret du citoyen — formation-civique.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 1),
  (v_civique, 'Le rôle du gouvernement est principalement :', 'qcm', '["de voter les lois","de déterminer et conduire la politique de la nation","de juger les citoyens","de modifier la Constitution seul"]', 'de déterminer et conduire la politique de la nation', 'Le gouvernement détermine et conduit la politique de la nation et veille à l''application des lois.', 'Livret du citoyen — formation-civique.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 2),
  (v_civique, 'Un employeur peut-il refuser d''embaucher quelqu''un à cause de son origine ?', 'qcm', '["Oui, c''est son droit","Non, c''est une discrimination interdite","Oui, si c''est une petite entreprise","Cela dépend du poste"]', 'Non, c''est une discrimination interdite', 'Refuser une embauche en raison de l''origine est une discrimination interdite et punie par la loi.', 'Livret du citoyen — formation-civique.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 2)
  ON CONFLICT (enonce) DO NOTHING;

  -- LANGUE (21)
  INSERT INTO questions (module_id, enonce, type, options_json, bonne_reponse, explication, source_officielle, date_verification, difficulte) VALUES
  (v_langue, 'Quel niveau de français est requis pour la naturalisation depuis 2026 ?', 'qcm', '["A2","B1","B2","C1"]', 'B2', 'Depuis le 1er janvier 2026, la naturalisation exige un niveau B2 à l''oral et à l''écrit (auparavant B1).', 'service-public.gouv.fr', '2026-06-19', 1),
  (v_langue, 'Quel niveau de français est requis pour une 1re carte de résident (10 ans) ?', 'qcm', '["A1","A2","B1","B2"]', 'B1', 'La première carte de résident exige le niveau B1, à l''oral comme à l''écrit.', 'service-public.gouv.fr', '2026-06-19', 1),
  (v_langue, 'Quel niveau de français est requis pour une 1re carte de séjour pluriannuelle ?', 'qcm', '["A2","B1","B2","C1"]', 'A2', 'La première carte de séjour pluriannuelle exige le niveau A2.', 'service-public.gouv.fr', '2026-06-19', 2),
  (v_langue, 'Avant 2026, quel niveau était demandé pour la naturalisation ?', 'qcm', '["A2","B1","B2","C2"]', 'B1', 'Avant le 1er janvier 2026, le niveau requis pour la naturalisation était le B1 ; il est désormais B2.', 'service-public.gouv.fr', '2026-06-19', 2),
  (v_langue, 'Que signifie le sigle CECRL ?', 'qcm', '["Comité d''État pour la citoyenneté","Cadre européen commun de référence pour les langues","Certificat européen de résidence légale","Conseil consultatif des résidents"]', 'Cadre européen commun de référence pour les langues', 'Le CECRL définit les niveaux de A1 à C2.', 'service-public.gouv.fr', '2026-06-19', 3),
  (v_langue, 'Le niveau B2 correspond à :', 'qcm', '["quelques mots de base","une autonomie simple","une maîtrise avancée (comprendre des textes complexes, s''exprimer clairement)","une maîtrise de locuteur natif"]', 'une maîtrise avancée (comprendre des textes complexes, s''exprimer clairement)', 'Le niveau B2 correspond à une maîtrise avancée : comprendre des textes complexes et s''exprimer de façon claire et structurée.', 'service-public.gouv.fr', '2026-06-19', 2),
  (v_langue, 'La condition de niveau de langue s''applique :', 'qcm', '["à chaque renouvellement","uniquement lors du premier accès au titre concerné","seulement pour les plus de 65 ans","jamais"]', 'uniquement lors du premier accès au titre concerné', 'La condition de langue s''applique lors du premier accès au titre ; elle n''est pas réexigée pour le simple renouvellement.', 'service-public.gouv.fr', '2026-06-19', 3),
  (v_langue, 'Quel test permet de justifier le niveau de français pour ces démarches ?', 'qcm', '["Le TOEIC","Le TCF IRN","Le SAT","Le GMAT"]', 'Le TCF IRN', 'Le TCF IRN (Test de connaissance du français — Intégration, Résidence et Nationalité) est conçu pour ces démarches.', 'service-public.gouv.fr', '2026-06-19', 2),
  (v_langue, 'Un diplôme français peut-il prouver le niveau de langue ?', 'qcm', '["Non, jamais","Oui (diplôme français comme le BAC ou un diplôme universitaire francophone)","Seulement un doctorat","Seulement à l''étranger"]', 'Oui (diplôme français comme le BAC ou un diplôme universitaire francophone)', 'Un diplôme délivré en France peut justifier le niveau de français requis.', 'service-public.gouv.fr', '2026-06-19', 2),
  (v_langue, 'Une attestation de niveau de langue (test) doit généralement dater de :', 'qcm', '["moins de 6 mois","moins de 2 ans","moins de 10 ans","peu importe"]', 'moins de 2 ans', 'Une attestation linguistique de moins de 2 ans est généralement demandée.', 'service-public.gouv.fr', '2026-06-19', 2),
  (v_langue, 'Pour la carte de résident, qui est dispensé de la condition de langue ?', 'qcm', '["les personnes de plus de 65 ans","les étudiants","les salariés","les commerçants"]', 'les personnes de plus de 65 ans', 'Les personnes âgées de plus de 65 ans sont dispensées de la condition de langue pour la carte de résident.', 'service-public.gouv.fr', '2026-06-19', 2),
  (v_langue, 'Le niveau B2 pour la naturalisation doit être justifié :', 'qcm', '["à l''oral seulement","à l''écrit seulement","à l''oral ET à l''écrit","par un simple entretien"]', 'à l''oral ET à l''écrit', 'Le niveau B2 porte sur l''expression et la compréhension, à l''oral comme à l''écrit.', 'service-public.gouv.fr', '2026-06-19', 2),
  (v_langue, 'DELF et DALF sont :', 'qcm', '["des cartes de séjour","des diplômes officiels de français langue étrangère","des impôts","des associations"]', 'des diplômes officiels de français langue étrangère', 'Le DELF et le DALF sont des diplômes officiels de FLE, reconnus pour justifier le niveau.', 'service-public.gouv.fr', '2026-06-19', 2),
  (v_langue, 'Le niveau A2 correspond à :', 'qcm', '["une maîtrise experte","un niveau élémentaire (situations simples de la vie courante)","le niveau d''un locuteur natif","aucune connaissance"]', 'un niveau élémentaire (situations simples de la vie courante)', 'Le niveau A2 correspond à un usage élémentaire : se débrouiller dans des situations courantes et simples.', 'service-public.gouv.fr', '2026-06-19', 1),
  (v_langue, 'Le niveau B1 correspond à :', 'qcm', '["aucune autonomie","une autonomie réelle dans la vie quotidienne et administrative","une maîtrise littéraire","le niveau natif"]', 'une autonomie réelle dans la vie quotidienne et administrative', 'Le niveau B1 traduit une autonomie réelle : comprendre l''essentiel et se débrouiller dans la plupart des situations.', 'service-public.gouv.fr', '2026-06-19', 2),
  (v_langue, 'La hausse des niveaux de langue découle de :', 'qcm', '["la loi du 9 décembre 1905","la loi du 26 janvier 2024","la Constitution de 1958","un décret de 1993"]', 'la loi du 26 janvier 2024', 'Le relèvement des niveaux résulte de la loi du 26 janvier 2024 sur l''immigration et l''intégration.', 'service-public.gouv.fr', '2026-06-19', 3),
  (v_langue, 'Pour la nationalité par mariage, quel niveau est requis depuis 2026 ?', 'qcm', '["A2","B1","B2","C1"]', 'B2', 'Depuis 2026, la déclaration de nationalité par mariage exige également le niveau B2.', 'service-public.gouv.fr', '2026-06-19', 2),
  (v_langue, 'Une incapacité médicale durable peut :', 'qcm', '["interdire la démarche","dispenser de la condition de langue, sur justificatif","accélérer la naturalisation","être ignorée"]', 'dispenser de la condition de langue, sur justificatif', 'Un certificat médical attestant une incapacité peut dispenser de la condition de langue.', 'service-public.gouv.fr', '2026-06-19', 3),
  (v_langue, 'Le niveau de français est aussi apprécié :', 'qcm', '["uniquement par le test","lors de l''entretien individuel en préfecture","par la mairie","par l''employeur"]', 'lors de l''entretien individuel en préfecture', 'Au-delà du justificatif, l''agent de préfecture apprécie l''expression orale lors de l''entretien.', 'immigration.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 2),
  (v_langue, 'Où passe-t-on le TCF IRN ?', 'qcm', '["en ligne sans contrôle","dans des centres agréés (France Éducation international)","à la mairie","au commissariat"]', 'dans des centres agréés (France Éducation international)', 'Le TCF IRN se passe dans des centres agréés ; il est conçu par France Éducation international.', 'service-public.gouv.fr', '2026-06-19', 3),
  (v_langue, 'Le niveau requis augmente selon le titre visé. Lequel est le plus élevé ?', 'qcm', '["carte de séjour pluriannuelle (A2)","carte de résident (B1)","nationalité française (B2)","ils sont identiques"]', 'nationalité française (B2)', 'L''exigence croît avec le titre : A2 pour la carte pluriannuelle, B1 pour la carte de résident, B2 pour la nationalité.', 'service-public.gouv.fr', '2026-06-19', 2)
  ON CONFLICT (enonce) DO NOTHING;

  -- CARTE RÉSIDENT (22) - seulement les premières lignes pour la version réduite, les ON CONFLICT gèrent les doublons
  INSERT INTO questions (module_id, enonce, type, options_json, bonne_reponse, explication, source_officielle, date_verification, difficulte) VALUES
  (v_carte, 'Quelle est la durée de validité de la carte de résident ?', 'qcm', '["3 ans","5 ans","10 ans","illimitée"]', '10 ans', 'La carte de résident est valable 10 ans et elle est renouvelable.', 'service-public.gouv.fr', '2026-06-19', 1),
  (v_carte, 'Durée de résidence régulière généralement exigée pour une carte de résident :', 'qcm', '["1 an","3 ans","5 ans","10 ans"]', '5 ans', 'La carte de résident suppose en règle générale 5 ans de résidence régulière et ininterrompue en France.', 'service-public.gouv.fr', '2026-06-19', 2),
  (v_carte, 'Quel niveau de langue est exigé pour une 1re carte de résident ?', 'qcm', '["A2","B1","B2","C1"]', 'B1', 'Une première carte de résident exige le niveau B1 du CECRL.', 'service-public.gouv.fr', '2026-06-19', 1),
  (v_carte, 'Quel examen faut-il réussir pour une 1re carte de résident ?', 'qcm', '["l''examen du code de la route","l''examen civique mention « carte de résident »","le TOEIC","aucun"]', 'l''examen civique mention « carte de résident »', 'Depuis le 1er janvier 2026, l''examen civique mention « carte de résident » est requis pour une première délivrance.', 'service-public.gouv.fr', '2026-06-19', 2),
  (v_carte, 'La condition de ressources pour la carte de résident suppose des revenus :', 'qcm', '["nuls","stables et suffisants (de l''ordre du SMIC)","supérieurs à 10 000 € par mois","provenant uniquement d''aides"]', 'stables et suffisants (de l''ordre du SMIC)', 'La carte de résident exige des ressources stables et suffisantes, appréciées au regard du SMIC.', 'service-public.gouv.fr', '2026-06-19', 2),
  (v_carte, 'La carte de résident permet :', 'qcm', '["de travailler librement sur tout le territoire","de travailler uniquement avec autorisation","de ne pas travailler","de voter aux présidentielles"]', 'de travailler librement sur tout le territoire', 'La carte de résident autorise à exercer toute activité professionnelle sur l''ensemble du territoire.', 'service-public.gouv.fr', '2026-06-19', 1),
  (v_carte, 'La carte de résident est souvent une étape avant :', 'qcm', '["le permis de conduire","la naturalisation","le mariage","la retraite"]', 'la naturalisation', 'La carte de résident, titre stable, précède fréquemment une demande de naturalisation.', 'service-public.gouv.fr', '2026-06-19', 1)
  ON CONFLICT (enonce) DO NOTHING;

  -- NATURALISATION (24) - premières lignes
  INSERT INTO questions (module_id, enonce, type, options_json, bonne_reponse, explication, source_officielle, date_verification, difficulte) VALUES
  (v_nat, 'Quelles sont les deux principales voies d''accès à la nationalité française ?', 'qcm', '["par achat et par héritage","par décret (naturalisation) et par déclaration (mariage)","par tirage au sort","par référendum"]', 'par décret (naturalisation) et par déclaration (mariage)', 'On accède à la nationalité notamment par décret (naturalisation) et par déclaration (par exemple le mariage).', 'immigration.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 2),
  (v_nat, 'Quel niveau de français faut-il pour la naturalisation depuis 2026 ?', 'qcm', '["A2","B1","B2","C1"]', 'B2', 'Depuis le 1er janvier 2026, la naturalisation exige le niveau B2 (auparavant B1).', 'service-public.gouv.fr', '2026-06-19', 1),
  (v_nat, 'L''examen civique de naturalisation prend la forme :', 'qcm', '["d''un oral de 2 heures","d''un QCM de 40 questions, seuil 32/40","d''une dissertation","d''un entretien collectif"]', 'd''un QCM de 40 questions, seuil 32/40', 'L''examen civique est un QCM de 40 questions ; il faut au moins 32 bonnes réponses (80 %) pour le réussir.', 'service-public.gouv.fr', '2026-06-19', 1),
  (v_nat, 'Une fois devenu français, on peut notamment :', 'qcm', '["voter aux élections et se présenter à certaines fonctions","échapper aux impôts","ne plus respecter la loi","perdre tout devoir"]', 'voter aux élections et se présenter à certaines fonctions', 'L''acquisition de la nationalité ouvre des droits civiques, dont le droit de vote et l''éligibilité.', 'immigration.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 1),
  (v_nat, 'Le dépôt du dossier de naturalisation se fait désormais principalement :', 'qcm', '["par courrier papier","en ligne (ANEF)","par fax","oralement"]', 'en ligne (ANEF)', 'La procédure est dématérialisée : le dépôt se fait en ligne via l''ANEF.', 'immigration.interieur.gouv.fr / service-public.gouv.fr', '2026-06-19', 1)
  ON CONFLICT (enonce) DO NOTHING;
END $$;
