-- Banque de 74 questions d'examen civique (livret du citoyen)
-- Résout dynamiquement le module_id du module examen_civique

DO $$
DECLARE
  v_module_id UUID;
BEGIN
  -- Trouver ou créer le module examen_civique
  SELECT id INTO v_module_id FROM public.modules WHERE categorie = 'examen_civique' LIMIT 1;
  IF v_module_id IS NULL THEN
    INSERT INTO public.modules (titre, description, categorie, ordre, icone)
    VALUES ('Examen civique', 'Préparation à l''examen de connaissances civiques : institutions, valeurs, histoire et symboles de la République française.', 'examen_civique', 4, 'GraduationCap')
    RETURNING id INTO v_module_id;
  END IF;

  -- Insert 74 questions (ON CONFLICT ignore les doublons par énoncé)
  INSERT INTO public.questions (module_id, enonce, type, options_json, bonne_reponse, explication, source_officielle, date_verification, difficulte) VALUES
  -- SYMBOLES ET VALEURS (1-15)
  (v_module_id, 'Quelle est la devise de la République française ?', 'qcm', '["Liberté, Égalité, Fraternité", "Liberté, Justice, Solidarité", "Égalité, Travail, Patrie", "Unité, République, Démocratie"]', 'Liberté, Égalité, Fraternité', 'La devise « Liberté, Égalité, Fraternité » figure dans l''article 2 de la Constitution de 1958.', 'https://www.service-public.fr/particuliers/vosdroits/F2215', '2026-01-15', 1),
  (v_module_id, 'Quel est l''hymne national de la France ?', 'qcm', '["La Marseillaise", "Le Chant du départ", "La Parisienne", "L''Internationale"]', 'La Marseillaise', 'La Marseillaise est l''hymne national depuis 1879, composée par Rouget de Lisle en 1792.', 'https://www.service-public.fr/particuliers/vosdroits/F2215', '2026-01-15', 1),
  (v_module_id, 'Quelles sont les couleurs du drapeau français, de gauche à droite ?', 'qcm', '["Bleu, blanc, rouge", "Rouge, blanc, bleu", "Bleu, rouge, blanc", "Blanc, bleu, rouge"]', 'Bleu, blanc, rouge', 'Le drapeau tricolore bleu, blanc, rouge est le drapeau national (article 2 de la Constitution).', 'https://www.conseil-constitutionnel.fr/la-constitution', '2026-01-15', 1),
  (v_module_id, 'Quel est le symbole féminin de la République française ?', 'qcm', '["Marianne", "Jeanne d''Arc", "La Liberté", "La Justice"]', 'Marianne', 'Marianne est la figure allégorique de la République française. Son buste est présent dans toutes les mairies.', 'https://www.elysee.fr/la-presidence/les-symboles-de-la-republique-francaise', '2026-01-15', 1),
  (v_module_id, 'Quelle fête nationale est célébrée le 14 juillet ?', 'qcm', '["La prise de la Bastille et la Fête de la Fédération", "La fin de la Seconde Guerre mondiale", "La proclamation de la République", "L''armistice de 1918"]', 'La prise de la Bastille et la Fête de la Fédération', 'Le 14 juillet commémore la prise de la Bastille (1789) et la Fête de la Fédération (1790).', 'https://www.service-public.fr/particuliers/actualites/A15642', '2026-01-15', 1),
  (v_module_id, 'Quel animal est un symbole non officiel de la France ?', 'qcm', '["Le coq", "L''aigle", "Le lion", "Le taureau"]', 'Le coq', 'Le coq gaulois est un symbole non officiel de la France, hérité de l''Antiquité (gallus = gaulois et coq en latin).', 'https://www.elysee.fr/la-presidence/les-symboles-de-la-republique-francaise', '2026-01-15', 1),
  (v_module_id, 'Quel principe signifie que tous les citoyens ont les mêmes droits devant la loi ?', 'qcm', '["L''égalité", "La liberté", "La fraternité", "La laïcité"]', 'L''égalité', 'L''égalité devant la loi est un principe fondamental : tous les citoyens sont égaux sans distinction d''origine, de race ou de religion (art. 1er de la Constitution).', 'https://www.conseil-constitutionnel.fr/la-constitution', '2026-01-15', 1),
  (v_module_id, 'Que signifie la laïcité en France ?', 'qcm', '["La séparation des Églises et de l''État", "L''interdiction de toute religion", "L''obligation d''être athée", "La supériorité d''une religion"]', 'La séparation des Églises et de l''État', 'La laïcité garantit la liberté de conscience et la séparation des Églises et de l''État (loi de 1905).', 'https://www.service-public.fr/particuliers/vosdroits/F2215', '2026-01-15', 1),
  (v_module_id, 'En quelle année la loi de séparation des Églises et de l''État a-t-elle été votée ?', 'qcm', '["1905", "1789", "1848", "1958"]', '1905', 'La loi du 9 décembre 1905 établit la séparation des Églises et de l''État, fondement de la laïcité française.', 'https://www.legifrance.gouv.fr/loda/id/LEGITEXT000006070169', '2026-01-15', 2),
  (v_module_id, 'Quelle est la langue officielle de la République française ?', 'qcm', '["Le français", "Le français et les langues régionales", "Il n''y a pas de langue officielle", "Le français et l''anglais"]', 'Le français', 'L''article 2 de la Constitution de 1958 dispose : « La langue de la République est le français. »', 'https://www.conseil-constitutionnel.fr/la-constitution', '2026-01-15', 1),
  (v_module_id, 'Depuis quand le suffrage est-il universel en France (hommes et femmes) ?', 'qcm', '["1944", "1789", "1848", "1936"]', '1944', 'Le droit de vote est accordé aux femmes par l''ordonnance du 21 avril 1944. Elles votent pour la première fois en 1945.', 'https://www.vie-publique.fr/fiches/23913-le-droit-de-vote-des-femmes', '2026-01-15', 2),
  (v_module_id, 'Quel est l''âge minimum pour voter en France ?', 'qcm', '["18 ans", "16 ans", "21 ans", "25 ans"]', '18 ans', 'En France, le droit de vote est acquis à 18 ans, âge de la majorité civile.', 'https://www.service-public.fr/particuliers/vosdroits/F1939', '2026-01-15', 1),
  (v_module_id, 'Quel texte de 1789 proclame les droits fondamentaux des citoyens ?', 'qcm', '["La Déclaration des droits de l''homme et du citoyen", "La Constitution de la Ve République", "Le Code civil", "Le préambule de 1946"]', 'La Déclaration des droits de l''homme et du citoyen', 'La DDHC du 26 août 1789 proclame les droits naturels et imprescriptibles de l''homme : liberté, propriété, sûreté, résistance à l''oppression.', 'https://www.conseil-constitutionnel.fr/le-bloc-de-constitutionnalite/declaration-des-droits-de-l-homme-et-du-citoyen-de-1789', '2026-01-15', 1),
  (v_module_id, 'Que garantit l''article 1er de la Constitution sur l''égalité ?', 'qcm', '["L''égalité devant la loi sans distinction d''origine, de race ou de religion", "Le droit au travail pour tous", "La gratuité de l''enseignement supérieur", "Le droit au logement"]', 'L''égalité devant la loi sans distinction d''origine, de race ou de religion', 'L''article 1er de la Constitution assure l''égalité de tous les citoyens sans distinction d''origine, de race ou de religion.', 'https://www.conseil-constitutionnel.fr/la-constitution', '2026-01-15', 2),
  (v_module_id, 'Quel est le régime politique de la France ?', 'qcm', '["Une République", "Une monarchie constitutionnelle", "Une fédération", "Un empire"]', 'Une République', 'La France est une République indivisible, laïque, démocratique et sociale (article 1er de la Constitution de 1958).', 'https://www.conseil-constitutionnel.fr/la-constitution', '2026-01-15', 1),

  -- INSTITUTIONS (16-35)
  (v_module_id, 'Qui est le chef de l''État en France ?', 'qcm', '["Le Président de la République", "Le Premier ministre", "Le Président de l''Assemblée nationale", "Le Président du Sénat"]', 'Le Président de la République', 'Le Président de la République est le chef de l''État. Il est élu au suffrage universel direct pour 5 ans.', 'https://www.elysee.fr/la-presidence/le-role-du-president', '2026-01-15', 1),
  (v_module_id, 'Pour combien d''années le Président de la République est-il élu ?', 'qcm', '["5 ans", "4 ans", "6 ans", "7 ans"]', '5 ans', 'Depuis la réforme de 2000 (quinquennat), le Président est élu pour 5 ans, renouvelable une fois.', 'https://www.vie-publique.fr/fiches/19427-la-duree-du-mandat-presidentiel', '2026-01-15', 1),
  (v_module_id, 'Qui nomme le Premier ministre ?', 'qcm', '["Le Président de la République", "L''Assemblée nationale", "Le Sénat", "Le Conseil constitutionnel"]', 'Le Président de la République', 'Le Président nomme le Premier ministre (article 8 de la Constitution). Il met fin à ses fonctions sur présentation de la démission du gouvernement.', 'https://www.conseil-constitutionnel.fr/la-constitution', '2026-01-15', 1),
  (v_module_id, 'Quel est le rôle du Premier ministre ?', 'qcm', '["Diriger l''action du gouvernement", "Présider le Conseil constitutionnel", "Voter les lois", "Commander les armées"]', 'Diriger l''action du gouvernement', 'Le Premier ministre dirige l''action du gouvernement, assure l''exécution des lois et dispose du pouvoir réglementaire (art. 21 de la Constitution).', 'https://www.gouvernement.fr/le-premier-ministre', '2026-01-15', 2),
  (v_module_id, 'Comment s''appelle le Parlement français ? De quoi est-il composé ?', 'qcm', '["L''Assemblée nationale et le Sénat", "L''Assemblée nationale uniquement", "Le Sénat et le Conseil d''État", "Le Congrès"]', 'L''Assemblée nationale et le Sénat', 'Le Parlement est bicaméral : il comprend l''Assemblée nationale (577 députés) et le Sénat (348 sénateurs).', 'https://www.assemblee-nationale.fr/connaissance/institution.asp', '2026-01-15', 1),
  (v_module_id, 'Quel est le rôle principal du Parlement ?', 'qcm', '["Voter les lois et contrôler le gouvernement", "Nommer le Président", "Juger les procès", "Diriger l''armée"]', 'Voter les lois et contrôler le gouvernement', 'Le Parlement vote la loi, contrôle l''action du gouvernement et évalue les politiques publiques (art. 24 de la Constitution).', 'https://www.assemblee-nationale.fr/connaissance/institution.asp', '2026-01-15', 1),
  (v_module_id, 'Pour combien d''années un député est-il élu ?', 'qcm', '["5 ans", "4 ans", "6 ans", "7 ans"]', '5 ans', 'Les députés sont élus au suffrage universel direct pour un mandat de 5 ans.', 'https://www.assemblee-nationale.fr/connaissance/elections-deputes.asp', '2026-01-15', 1),
  (v_module_id, 'Pour combien d''années un sénateur est-il élu ?', 'qcm', '["6 ans", "5 ans", "7 ans", "9 ans"]', '6 ans', 'Les sénateurs sont élus pour 6 ans au suffrage universel indirect. Le Sénat est renouvelé par moitié tous les 3 ans.', 'https://www.senat.fr/role/fiche/elections.html', '2026-01-15', 2),
  (v_module_id, 'Quel est le rôle du Conseil constitutionnel ?', 'qcm', '["Vérifier la conformité des lois à la Constitution", "Voter les lois", "Nommer les ministres", "Juger les crimes"]', 'Vérifier la conformité des lois à la Constitution', 'Le Conseil constitutionnel veille à la conformité des lois à la Constitution et juge les contentieux électoraux.', 'https://www.conseil-constitutionnel.fr/le-conseil-constitutionnel', '2026-01-15', 2),
  (v_module_id, 'Où siège l''Assemblée nationale ?', 'qcm', '["Au Palais Bourbon", "Au Palais du Luxembourg", "À l''Élysée", "À Matignon"]', 'Au Palais Bourbon', 'L''Assemblée nationale siège au Palais Bourbon, dans le 7e arrondissement de Paris.', 'https://www.assemblee-nationale.fr/connaissance/palais-bourbon.asp', '2026-01-15', 2),
  (v_module_id, 'Où siège le Sénat ?', 'qcm', '["Au Palais du Luxembourg", "Au Palais Bourbon", "À l''Élysée", "Au Palais de Justice"]', 'Au Palais du Luxembourg', 'Le Sénat siège au Palais du Luxembourg, dans le 6e arrondissement de Paris.', 'https://www.senat.fr/visite/palais.html', '2026-01-15', 2),
  (v_module_id, 'Qui peut proposer une loi en France ?', 'qcm', '["Le gouvernement et les parlementaires", "Le Président seul", "Les citoyens directement", "Les juges"]', 'Le gouvernement et les parlementaires', 'L''initiative des lois appartient au Premier ministre (projet de loi) et aux parlementaires (proposition de loi) — art. 39 de la Constitution.', 'https://www.assemblee-nationale.fr/connaissance/procedure-legislative.asp', '2026-01-15', 2),
  (v_module_id, 'Qu''est-ce que le suffrage universel direct ?', 'qcm', '["Tous les citoyens majeurs votent directement pour élire un représentant", "Seuls les hommes votent", "Des grands électeurs votent à la place des citoyens", "Le vote est réservé aux propriétaires"]', 'Tous les citoyens majeurs votent directement pour élire un représentant', 'Le suffrage universel direct signifie que tous les citoyens majeurs participent directement au vote sans intermédiaire.', 'https://www.vie-publique.fr/fiches/23912-les-differents-modes-de-scrutin', '2026-01-15', 1),
  (v_module_id, 'Quelle est la plus haute juridiction de l''ordre judiciaire ?', 'qcm', '["La Cour de cassation", "Le Conseil d''État", "La Cour d''appel", "Le Tribunal judiciaire"]', 'La Cour de cassation', 'La Cour de cassation est la plus haute juridiction de l''ordre judiciaire. Elle ne juge pas les faits mais vérifie l''application du droit.', 'https://www.courdecassation.fr/la-cour-de-cassation', '2026-01-15', 2),
  (v_module_id, 'Quelle est la plus haute juridiction de l''ordre administratif ?', 'qcm', '["Le Conseil d''État", "La Cour de cassation", "Le Tribunal administratif", "La Cour des comptes"]', 'Le Conseil d''État', 'Le Conseil d''État est la plus haute juridiction administrative et conseiller du gouvernement pour la rédaction des lois.', 'https://www.conseil-etat.fr/le-conseil-d-etat', '2026-01-15', 2),
  (v_module_id, 'Qui assure l''intérim du Président en cas d''empêchement ?', 'qcm', '["Le Président du Sénat", "Le Premier ministre", "Le Président de l''Assemblée nationale", "Le Ministre de l''Intérieur"]', 'Le Président du Sénat', 'En cas de vacance ou d''empêchement, le Président du Sénat assure l''intérim (article 7 de la Constitution).', 'https://www.conseil-constitutionnel.fr/la-constitution', '2026-01-15', 2),
  (v_module_id, 'Comment s''appelle la résidence officielle du Président de la République ?', 'qcm', '["Le Palais de l''Élysée", "Le Palais Bourbon", "L''Hôtel Matignon", "Le Palais du Luxembourg"]', 'Le Palais de l''Élysée', 'Le Palais de l''Élysée, situé rue du Faubourg-Saint-Honoré à Paris, est la résidence officielle du Président depuis 1848.', 'https://www.elysee.fr/la-presidence/le-palais-de-l-elysee', '2026-01-15', 1),

  -- HISTOIRE (36-50)
  (v_module_id, 'En quelle année a eu lieu la Révolution française ?', 'qcm', '["1789", "1799", "1776", "1815"]', '1789', 'La Révolution française débute en 1789 avec la prise de la Bastille le 14 juillet et la Déclaration des droits de l''homme le 26 août.', 'https://www.elysee.fr/la-presidence/14-juillet', '2026-01-15', 1),
  (v_module_id, 'En quelle année la Ire République française a-t-elle été proclamée ?', 'qcm', '["1792", "1789", "1804", "1848"]', '1792', 'La Ire République est proclamée le 22 septembre 1792, après l''abolition de la royauté.', 'https://www.vie-publique.fr/fiches/19509-les-cinq-republiques', '2026-01-15', 2),
  (v_module_id, 'En quelle année la Ve République a-t-elle été instaurée ?', 'qcm', '["1958", "1946", "1968", "1981"]', '1958', 'La Ve République est instaurée par la Constitution du 4 octobre 1958, sous l''impulsion du Général de Gaulle.', 'https://www.conseil-constitutionnel.fr/la-constitution', '2026-01-15', 1),
  (v_module_id, 'Qui a fondé la Ve République ?', 'qcm', '["Charles de Gaulle", "François Mitterrand", "Napoléon Bonaparte", "Georges Clemenceau"]', 'Charles de Gaulle', 'Le Général de Gaulle est le fondateur de la Ve République et son premier Président (1959-1969).', 'https://www.elysee.fr/charles-de-gaulle', '2026-01-15', 1),
  (v_module_id, 'Quel événement est commémoré le 11 novembre ?', 'qcm', '["L''armistice de la Première Guerre mondiale (1918)", "La fin de la Seconde Guerre mondiale", "La Révolution française", "La libération de Paris"]', 'L''armistice de la Première Guerre mondiale (1918)', 'Le 11 novembre commémore l''armistice signé en 1918 mettant fin à la Première Guerre mondiale.', 'https://www.defense.gouv.fr/memoire/commemorations/11-novembre', '2026-01-15', 1),
  (v_module_id, 'Quel événement est commémoré le 8 mai ?', 'qcm', '["La victoire des Alliés en 1945 (fin de la Seconde Guerre mondiale en Europe)", "La prise de la Bastille", "L''armistice de 1918", "La proclamation de la République"]', 'La victoire des Alliés en 1945 (fin de la Seconde Guerre mondiale en Europe)', 'Le 8 mai 1945 marque la capitulation de l''Allemagne nazie et la fin de la Seconde Guerre mondiale en Europe.', 'https://www.defense.gouv.fr/memoire/commemorations/8-mai', '2026-01-15', 1),
  (v_module_id, 'Qu''est-ce que le siècle des Lumières ?', 'qcm', '["Un mouvement intellectuel du XVIIIe siècle prônant la raison et la liberté", "Une période de guerres religieuses", "La Renaissance artistique du XVIe siècle", "L''industrialisation du XIXe siècle"]', 'Un mouvement intellectuel du XVIIIe siècle prônant la raison et la liberté', 'Le siècle des Lumières (XVIIIe s.) est un mouvement intellectuel porté par Voltaire, Rousseau, Montesquieu, Diderot, qui a influencé la Révolution.', 'https://www.vie-publique.fr/fiches/268773-les-grands-principes-des-lumieres', '2026-01-15', 2),
  (v_module_id, 'Quand l''esclavage a-t-il été définitivement aboli en France ?', 'qcm', '["1848", "1789", "1794", "1905"]', '1848', 'L''esclavage est définitivement aboli le 27 avril 1848 par le décret de Victor Schœlcher sous la IIe République.', 'https://www.vie-publique.fr/fiches/273912-la-commemoration-de-labolition-de-lesclavage', '2026-01-15', 2),
  (v_module_id, 'Qu''est-ce que la Déclaration universelle des droits de l''homme (1948) ?', 'qcm', '["Un texte international proclamant les droits fondamentaux de tous les êtres humains", "La Constitution française", "Un traité de paix", "Une loi européenne"]', 'Un texte international proclamant les droits fondamentaux de tous les êtres humains', 'La DUDH, adoptée le 10 décembre 1948 par l''ONU, proclame les droits fondamentaux de tous les êtres humains sans distinction.', 'https://www.un.org/fr/about-us/universal-declaration-of-human-rights', '2026-01-15', 2),
  (v_module_id, 'Qui a écrit « Du contrat social » ?', 'qcm', '["Jean-Jacques Rousseau", "Voltaire", "Montesquieu", "Denis Diderot"]', 'Jean-Jacques Rousseau', 'Jean-Jacques Rousseau a publié Du contrat social en 1762, œuvre majeure de la philosophie politique des Lumières.', 'https://www.vie-publique.fr/fiches/268773-les-grands-principes-des-lumieres', '2026-01-15', 2),
  (v_module_id, 'Quel philosophe a développé la théorie de la séparation des pouvoirs ?', 'qcm', '["Montesquieu", "Voltaire", "Rousseau", "Diderot"]', 'Montesquieu', 'Montesquieu développe la séparation des pouvoirs (législatif, exécutif, judiciaire) dans De l''esprit des lois (1748).', 'https://www.conseil-constitutionnel.fr/la-constitution', '2026-01-15', 2),
  (v_module_id, 'Quels sont les trois pouvoirs séparés en démocratie ?', 'qcm', '["Législatif, exécutif et judiciaire", "Politique, économique et militaire", "Local, régional et national", "Religieux, civil et militaire"]', 'Législatif, exécutif et judiciaire', 'La séparation des pouvoirs distingue : le législatif (faire les lois), l''exécutif (appliquer les lois) et le judiciaire (juger).', 'https://www.conseil-constitutionnel.fr/la-constitution', '2026-01-15', 1),
  (v_module_id, 'En quelle année le droit de vote a-t-il été accordé aux femmes en France ?', 'qcm', '["1944", "1936", "1958", "1968"]', '1944', 'L''ordonnance du 21 avril 1944 accorde le droit de vote et d''éligibilité aux femmes. Elles votent pour la première fois aux municipales d''avril 1945.', 'https://www.vie-publique.fr/fiches/23913-le-droit-de-vote-des-femmes', '2026-01-15', 1),
  (v_module_id, 'Quand la peine de mort a-t-elle été abolie en France ?', 'qcm', '["1981", "1968", "1946", "2001"]', '1981', 'La peine de mort est abolie le 9 octobre 1981 sous la présidence de François Mitterrand, portée par Robert Badinter.', 'https://www.vie-publique.fr/fiches/268803-labolition-de-la-peine-de-mort', '2026-01-15', 2),

  -- DROITS ET DEVOIRS (51-62)
  (v_module_id, 'L''école est-elle obligatoire en France ? Jusqu''à quel âge ?', 'qcm', '["Oui, de 3 à 16 ans", "Oui, de 6 à 14 ans", "Non, elle est facultative", "Oui, de 6 à 18 ans"]', 'Oui, de 3 à 16 ans', 'L''instruction est obligatoire de 3 à 16 ans depuis la loi du 26 juillet 2019. L''obligation de formation est étendue jusqu''à 18 ans.', 'https://www.education.gouv.fr/l-obligation-scolaire-6830', '2026-01-15', 1),
  (v_module_id, 'L''école publique est-elle gratuite en France ?', 'qcm', '["Oui, l''enseignement public est gratuit et laïque", "Non, il faut toujours payer", "Seulement au lycée", "Seulement pour les Français"]', 'Oui, l''enseignement public est gratuit et laïque', 'L''école publique est gratuite (loi du 16 juin 1881) et laïque (loi du 28 mars 1882).', 'https://www.education.gouv.fr/les-grands-principes-du-systeme-educatif-6382', '2026-01-15', 1),
  (v_module_id, 'Le vote est-il obligatoire en France ?', 'qcm', '["Non, c''est un droit mais pas une obligation légale", "Oui, on peut être sanctionné", "Oui, depuis 2020", "Uniquement pour les présidentielles"]', 'Non, c''est un droit mais pas une obligation légale', 'Le vote est un droit civique mais n''est pas légalement obligatoire en France, contrairement à d''autres pays (Belgique, Australie).', 'https://www.service-public.fr/particuliers/vosdroits/F1939', '2026-01-15', 1),
  (v_module_id, 'Quel est le devoir fiscal de tout résident en France ?', 'qcm', '["Payer ses impôts", "Voter", "Faire son service militaire", "Parler français"]', 'Payer ses impôts', 'Contribuer aux charges publiques par l''impôt est un devoir civique inscrit dans la DDHC de 1789 (article 13).', 'https://www.impots.gouv.fr', '2026-01-15', 1),
  (v_module_id, 'La Journée Défense et Citoyenneté (JDC) est-elle obligatoire ?', 'qcm', '["Oui, pour tous les jeunes Français de 16 à 25 ans", "Non, elle est facultative", "Uniquement pour les garçons", "Seulement en temps de guerre"]', 'Oui, pour tous les jeunes Français de 16 à 25 ans', 'La JDC est obligatoire pour tous les jeunes Français. L''attestation est nécessaire pour passer les examens et concours publics.', 'https://www.service-public.fr/particuliers/vosdroits/F871', '2026-01-15', 2),
  (v_module_id, 'Quels sont les droits fondamentaux garantis par la Constitution ?', 'qcm', '["Liberté, égalité, sûreté, propriété, résistance à l''oppression", "Logement, travail, vacances, retraite", "Santé, éducation, loisirs", "Vote, mariage, divorce"]', 'Liberté, égalité, sûreté, propriété, résistance à l''oppression', 'La DDHC de 1789 (art. 2) proclame les droits naturels : liberté, propriété, sûreté et résistance à l''oppression.', 'https://www.conseil-constitutionnel.fr/le-bloc-de-constitutionnalite/declaration-des-droits-de-l-homme-et-du-citoyen-de-1789', '2026-01-15', 2),
  (v_module_id, 'La France garantit-elle la liberté d''expression ?', 'qcm', '["Oui, dans les limites fixées par la loi", "Oui, sans aucune limite", "Non", "Seulement pour la presse"]', 'Oui, dans les limites fixées par la loi', 'La liberté d''expression est un droit fondamental (art. 11 DDHC), limité par la loi (diffamation, incitation à la haine, etc.).', 'https://www.conseil-constitutionnel.fr/le-bloc-de-constitutionnalite/declaration-des-droits-de-l-homme-et-du-citoyen-de-1789', '2026-01-15', 2),
  (v_module_id, 'La France autorise-t-elle la polygamie ?', 'qcm', '["Non, la polygamie est interdite", "Oui, sous conditions", "Uniquement pour les étrangers", "La loi ne dit rien"]', 'Non, la polygamie est interdite', 'La polygamie est interdite en France. Le mariage ne peut être contracté qu''entre deux personnes (art. 147 du Code civil).', 'https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000006421962', '2026-01-15', 1),
  (v_module_id, 'L''égalité homme-femme est-elle un principe constitutionnel en France ?', 'qcm', '["Oui", "Non", "Seulement depuis 2020", "Uniquement dans le travail"]', 'Oui', 'L''égalité entre les femmes et les hommes est un principe constitutionnel (préambule de 1946, art. 1er de la Constitution).', 'https://www.conseil-constitutionnel.fr/la-constitution', '2026-01-15', 1),
  (v_module_id, 'Quel est l''âge de la majorité civile en France ?', 'qcm', '["18 ans", "16 ans", "21 ans", "14 ans"]', '18 ans', 'La majorité est fixée à 18 ans (art. 414 du Code civil). À cet âge, on acquiert la pleine capacité juridique.', 'https://www.service-public.fr/particuliers/vosdroits/F1194', '2026-01-15', 1),
  (v_module_id, 'Quel numéro appeler en cas d''urgence en France ?', 'qcm', '["15, 17 ou 18 (ou 112 pour l''Europe)", "911", "999", "111"]', '15, 17 ou 18 (ou 112 pour l''Europe)', '15 = SAMU, 17 = Police, 18 = Pompiers. Le 112 est le numéro d''urgence européen, accessible partout en France.', 'https://www.service-public.fr/particuliers/vosdroits/F32841', '2026-01-15', 1),

  -- ORGANISATION TERRITORIALE ET EUROPE (63-74)
  (v_module_id, 'Combien de régions la France métropolitaine compte-t-elle ?', 'qcm', '["13", "18", "22", "27"]', '13', 'Depuis 2016, la France métropolitaine compte 13 régions. Avec les outre-mer, on arrive à 18 régions au total.', 'https://www.vie-publique.fr/fiches/19620-les-regions', '2026-01-15', 2),
  (v_module_id, 'Qu''est-ce qu''une commune en France ?', 'qcm', '["La plus petite division administrative, dirigée par un maire", "Une région", "Un département", "Un quartier"]', 'La plus petite division administrative, dirigée par un maire', 'La commune est la plus petite collectivité territoriale française. Elle est administrée par un conseil municipal élu, dirigé par le maire.', 'https://www.vie-publique.fr/fiches/19618-la-commune', '2026-01-15', 1),
  (v_module_id, 'Qui élit le maire d''une commune ?', 'qcm', '["Le conseil municipal", "Les citoyens directement", "Le préfet", "Le Président de la République"]', 'Le conseil municipal', 'Le maire est élu par les conseillers municipaux lors de la première séance du conseil après les élections municipales.', 'https://www.vie-publique.fr/fiches/19618-la-commune', '2026-01-15', 2),
  (v_module_id, 'La France est-elle membre fondateur de l''Union européenne ?', 'qcm', '["Oui", "Non", "Elle a rejoint l''UE en 1992", "Elle n''est pas membre"]', 'Oui', 'La France est l''un des 6 membres fondateurs de la Communauté européenne (1957, Traité de Rome), devenue l''Union européenne.', 'https://www.vie-publique.fr/fiches/20309-les-etapes-de-la-construction-europeenne', '2026-01-15', 1),
  (v_module_id, 'Quelle est la monnaie utilisée en France ?', 'qcm', '["L''euro", "Le franc", "Le dollar", "La livre"]', 'L''euro', 'L''euro est la monnaie de la France depuis le 1er janvier 2002 (pièces et billets). La France fait partie de la zone euro.', 'https://www.service-public.fr/particuliers/actualites/A14078', '2026-01-15', 1),
  (v_module_id, 'Combien d''États membres compte l''Union européenne (2024) ?', 'qcm', '["27", "28", "25", "30"]', '27', 'L''Union européenne compte 27 États membres depuis le Brexit (sortie du Royaume-Uni en 2020).', 'https://www.vie-publique.fr/fiches/20309-les-etapes-de-la-construction-europeenne', '2026-01-15', 2),
  (v_module_id, 'Qu''est-ce que l''espace Schengen ?', 'qcm', '["Un espace de libre circulation sans contrôle aux frontières intérieures", "Un accord militaire", "Une zone monétaire", "Un tribunal européen"]', 'Un espace de libre circulation sans contrôle aux frontières intérieures', 'L''espace Schengen permet la libre circulation des personnes entre 27 pays européens sans contrôle aux frontières intérieures.', 'https://www.vie-publique.fr/fiches/20399-lespace-schengen', '2026-01-15', 2),
  (v_module_id, 'Qu''est-ce que le préfet en France ?', 'qcm', '["Le représentant de l''État dans le département", "Le chef du conseil départemental", "Un magistrat", "Le maire du chef-lieu"]', 'Le représentant de l''État dans le département', 'Le préfet est le représentant de l''État dans le département. Il veille à l''exécution des lois et à l''ordre public.', 'https://www.vie-publique.fr/fiches/19621-le-prefet', '2026-01-15', 2),
  (v_module_id, 'Que sont les DROM (anciens DOM-TOM) ?', 'qcm', '["Les départements et régions d''outre-mer français", "Des pays étrangers partenaires", "Des régions métropolitaines", "Des anciennes colonies indépendantes"]', 'Les départements et régions d''outre-mer français', 'Les DROM (Guadeloupe, Martinique, Guyane, Réunion, Mayotte) sont des territoires français situés hors de la métropole.', 'https://www.vie-publique.fr/fiches/19624-les-collectivites-d-outre-mer', '2026-01-15', 2),
  (v_module_id, 'Quel est le rôle de la Cour européenne des droits de l''homme ?', 'qcm', '["Garantir le respect de la Convention européenne des droits de l''homme", "Voter les lois européennes", "Gérer la monnaie européenne", "Diriger l''armée européenne"]', 'Garantir le respect de la Convention européenne des droits de l''homme', 'La CEDH, siégeant à Strasbourg, veille au respect de la Convention européenne des droits de l''homme par les 46 États membres du Conseil de l''Europe.', 'https://www.echr.coe.int/Pages/home.aspx?p=home&c=fre', '2026-01-15', 2),
  (v_module_id, 'Où se trouve le siège du Parlement européen ?', 'qcm', '["À Strasbourg", "À Bruxelles", "À Luxembourg", "À Paris"]', 'À Strasbourg', 'Le siège officiel du Parlement européen est à Strasbourg, bien que des sessions se tiennent aussi à Bruxelles.', 'https://www.europarl.europa.eu/about-parliament/fr', '2026-01-15', 2),
  (v_module_id, 'La France fait-elle partie de l''OTAN ?', 'qcm', '["Oui, elle est membre fondateur", "Non", "Elle a quitté l''OTAN en 1966", "Elle n''est qu''observatrice"]', 'Oui, elle est membre fondateur', 'La France est membre fondateur de l''OTAN (1949). Elle a quitté le commandement intégré en 1966 mais l''a réintégré en 2009.', 'https://www.diplomatie.gouv.fr/fr/politique-etrangere-de-la-france/securite-desarmement-et-non-proliferation/nos-alliances-et-cooperations/l-otan/', '2026-01-15', 2)

  ON CONFLICT DO NOTHING;
END $$;
